os:
  - osx
global:
  - ANDROID_COMPONENTS=build-tools-25.0.1,android-24,extra-android-support,extra-google-google_play_services,extra-google-m2repository,extra-android-m2repository
  - ANDROID_LICENSES=android-sdk-license-c81a61d9
  - MONO_VERSION=6.10.0
  - MONO_ANDROID_VERSION=7.0.2-42
dotnet: 2.0
language: csharp
install:
  - dotnet tool install --global boots
  - boots https://aka.ms/xamarin-android-commercial-d16-2-macos
  - nuget restore CloudStreamForms/CloudStreamForms.Android/CloudStreamForms.Android.csproj
script:
  - msbuild /t:SignAndroidPackage /p:Configuration=Release CloudStreamForms/CloudStreamForms.Android/CloudStreamForms.Android.csproj
