os: windows
language: csharp
mono: none
solution: CloudStreamForms.sln
dotnet: 2.2
install:
  - dotnet dotnet tool install --global boots 
  - boots https://aka.ms/xamarin-android-commercial-d16-2-windows
script:
  - dotnet restore CloudStreamForms/CloudStreamForms.Android/CloudStreamsForms.Android.csproj
  - dotnet publish -r android CloudStreamForms/CloudStreamForms.Android/CloudStreamForms.Android.csproj --self-contained true
