os: osx
language: csharp
env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
    - AndroidSdkDirectory=../../android-sdk/android-sdk-macosx
dotnet: 3.1.200
mono: 6.6.0
branches:
  only:
    - master
script:
  - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/version-2/android-sdk-installer -o android-sdk-installer
  - chmod u+x android-sdk-installer
  - ./android-sdk-installer --dir=./android-sdk --install=build-tools-28.0.0,android-28,platform-tools-28.0.0 --accept="android-sdk-license-e6a904e8|android-sdk-license-e6a904e8|android-sdk-license-e6a904e8"
  - brew update
  - brew cask install adoptopenjdk/openjdk/adoptopenjdk8
  - export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
  - dotnet tool install --global boots > nul
  - boots https://aka.ms/xamarin-android-commercial-d16-4-macos
  - nuget restore CloudStreamForms.sln
  - travis_wait 200 msbuild /p:Configuration=Release /p:AndroidBuildApplicationPackage=true /t:Clean\;Build\;SignAndroidPackage CloudStreamForms.sln
