os: windows
language: csharp
mono: none
dotnet: 2.1.502
solution: CloudStreamForms.sln
script:
  - dotnet restore
  - msbuild /t:SignAndroidPackage /p:Configuration=Release CloudStreamForms/CloudStreamForms.Android/CloudStreamForms.Android.csproj
