language: csharp
install:
  - nuget restore CloudStreamForms/CloudStreamForms.Android/CloudStreamForms.Android.csproj
script:
  - msbuild /t:SignAndroidPackage /p:Configuration=Release CloudStreamForms/CloudStreamForms.Android/CloudStreamForms.Android.csproj
