before_build:
  - nuget restore CloudStreamForms.sln
build_script:
  - msbuild /m /p:Configuration=Release /p:AndroidSupportedAbis=2212329 /t:PackageForAndroid CloudStreamForms/CloudStreamForms.Android/CloudStreamForms.Android.csproj
artifacts:
  - path: 'CloudStreamForms\CloudStreamForms.Android\bin\Release\com.CloudStreamForms.CloudStreamForms.apk'
