name: Build App

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build app
    runs-on: macos-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build app
        run: |
          nuget restore CloudStreamForms.sln
          msbuild /m /p:OutputPath=bin.armeabi-v7a /p:Configuration=Release /p:AndroidSupportedAbis=armeabi-v7a /t:SignAndroidPackage CloudStreamForms/CloudStreamForms.Android/CloudStreamForms.Android.csproj

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: CloudStream
          path: CloudStreamForms/CloudStreamForms.Android/bin.armeabi-v7a/com.CloudStreamForms.CloudStreamForms-Signed.apk
