before_build:
  - nuget restore CloudStreamForms.sln
build_script:
  - msbuild /m /p:OutputPath=bin.armeabi-v7a /p:Configuration=Release /p:AndroidSupportedAbis=armeabi-v7a /t:SignAndroidPackage CloudStreamForms/CloudStreamForms.Android/CloudStreamForms.Android.csproj
  - msbuild /m /p:OutputPath=bin.arm64-v8a /p:Configuration=Release /p:AndroidSupportedAbis=arm64-v8a /t:SignAndroidPackage CloudStreamForms/CloudStreamForms.Android/CloudStreamForms.Android.csproj
  - msbuild /m /p:OutputPath=bin.x86 /p:Configuration=Release /p:AndroidSupportedAbis=x86 /t:SignAndroidPackage CloudStreamForms/CloudStreamForms.Android/CloudStreamForms.Android.csproj
artifacts:
  - path: 'CloudStreamForms\CloudStreamForms.Android\bin.armeabi-v7a\com.CloudStreamForms.CloudStreamForms-Signed.apk'
  - path: 'CloudStreamForms\CloudStreamForms.Android\bin.arm64-v8a\com.CloudStreamForms.CloudStreamForms-Signed.apk'
  - path: 'CloudStreamForms\CloudStreamForms.Android\bin.x86\com.CloudStreamForms.CloudStreamForms-Signed.apk'
